# Generated by Django 2.1.1 on 2018-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=380)),
                ('category', models.TextField()),
                ('city', models.CharField(choices=[('WL', 'West Lafayette'), ('L', 'Lafayette')], default='L', max_length=2)),
                ('salary', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(max_length=10000)),
                ('instructions', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
