# Generated by Django 2.1.1 on 2018-09-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180921_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='highlight_job',
            field=models.BooleanField(default=False),
        ),
    ]
