# Generated by Django 2.1.1 on 2018-09-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180921_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=380, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='highlight_job',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
